name: Liquibase Update

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v7
        with:
          operation: 'update'
          classpath: 'db/changelog'
          changeLogFile: 'changes/create.sql'
          username: root
          password: ${{ secrets.DB_PWD }}
          url: ${{ secrets.DB_URL }}
