name: Liquibase Update

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update@v4.23.2
        with:
          # The root changelog
          # string
          # Required
          changelogFile: "example-changelog.sql"

          # The JDBC database connection URL
          # string
          # Required
          url: ${{ secrets.DB_URL }}