name: Liquibase Update

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update@v4.23.2
        with:
          changelogFile: "example-changelog.sql"
          driver: "com.mysql.jdbc.Driver"
          url: ${{ secrets.DB_URL }}